name: "Publish Conda package to Anaconda.org"
description: "Build and Publish conda package to Anaconda"
author: "Andrew Prokhorenkov, modified by Maxime Borry"
branding:
  icon: "package"
  color: "purple"
inputs:
  subDir:
    description: "Sub-directory with conda recipe"
    default: "."
  anacondaToken:
    description: "Anaconda access Token"
runs:
  using: "docker"
  image: "Dockerfile"
